import { SurveyQuestion } from "./types";

export const weddingSurveySchema: SurveyQuestion[] = [
  {
    id: "partnerNames",
    label: "Who's getting married?",
    type: "text",
    placeholder: "Alex & Jordan",
    description: "Optional, but helpful for a more personal plan.",
  },
  {
    id: "totalBudget",
    label: "Total wedding budget",
    type: "number",
    required: true,
    min: 1000,
    placeholder: "12000",
    description: "Use your full target budget, not just vendor spend.",
  },
  {
    id: "guestCount",
    label: "Estimated guest count",
    type: "number",
    required: true,
    min: 10,
    placeholder: "75",
  },
  {
    id: "location",
    label: "City or region",
    type: "text",
    required: true,
    placeholder: "Austin, TX",
  },
  {
    id: "season",
    label: "Preferred season",
    type: "select",
    required: true,
    placeholder: "Select a season",
    options: [
      { label: "Flexible", value: "flexible" },
      { label: "Spring", value: "spring" },
      { label: "Summer", value: "summer" },
      { label: "Fall", value: "fall" },
      { label: "Winter", value: "winter" },
    ],
  },
  {
    id: "targetDate",
    label: "Target date or timing",
    type: "text",
    placeholder: "October 2026 or flexible Saturday",
  },
  {
    id: "priorities",
    label: "Top priorities",
    type: "multiselect",
    required: true,
    options: [
      { label: "Food", value: "food" },
      { label: "Venue", value: "venue" },
      { label: "Photo / Video", value: "photo-video" },
      { label: "Music", value: "music" },
      { label: "Decor", value: "decor" },
      { label: "Attire", value: "attire" },
      { label: "Guest Experience", value: "guest-experience" },
      { label: "Low Stress Planning", value: "low-stress" },
    ],
    description: "Choose the areas worth protecting when tradeoffs are needed.",
  },
  {
    id: "alcoholAllowed",
    label: "Will you serve alcohol?",
    type: "select",
    placeholder: "Select an option",
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
      { label: "Maybe / Not sure", value: "maybe" },
    ],
  },
  {
    id: "diyWillingness",
    label: "How much DIY are you open to?",
    type: "select",
    placeholder: "Select an option",
    options: [
      { label: "None", value: "none" },
      { label: "Some", value: "some" },
      { label: "A lot", value: "high" },
    ],
  },
  {
    id: "style",
    label: "Preferred style",
    type: "select",
    required: true,
    placeholder: "Select a style",
    options: [
      { label: "Casual", value: "casual" },
      { label: "Classic", value: "classic" },
      { label: "Garden", value: "garden" },
      { label: "Modern", value: "modern" },
      { label: "Rustic", value: "rustic" },
      { label: "Minimal", value: "minimal" },
      { label: "Cultural / Traditional", value: "cultural-traditional" },
    ],
  },
  {
    id: "ceremonyType",
    label: "Wedding format",
    type: "text",
    placeholder: "Ceremony and reception, brunch wedding, courthouse plus dinner",
  },
  {
    id: "cateringPreference",
    label: "Food approach",
    type: "text",
    placeholder: "Buffet, taco bar, brunch, plated dinner",
  },
  {
    id: "constraints",
    label: "Constraints or non-negotiables",
    type: "textarea",
    placeholder: "No Friday events, need wheelchair access, no debt, must be family friendly",
    description: "Budget constraints, accessibility, cultural needs, venue restrictions, or hard preferences.",
  },
];
